name: Deploy AWS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - name: Clone do projeto
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "gustavovvbs"
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gustavovvbs/pi-zambon:${{ github.sha }}

      - name: Deploy with MySQL
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_TEST }}
          username: "ubuntu"
          key: ${{ secrets.KEY_TEST }}
          port: 22
          script: |
            docker stop pi-zambon mysql-pi-zambon || true
            docker rm --force pi-zambon mysql-pi-zambon || true
            
            docker network create pi-zambon-network || true
            
            docker run -d \
              --name mysql-pi-zambon \
              --network pi-zambon-network \
              -e MYSQL_ROOT_PASSWORD=rootpassword123 \
              -e MYSQL_DATABASE=pf_zambon_db \
              -e MYSQL_USER=app_user \
              -e MYSQL_PASSWORD=app_password123 \
              -v mysql_data:/var/lib/mysql \
              -p 3306:3306 \
              mysql:8.0
            
            sleep 20
            
            docker run -d \
              --name pi-zambon \
              --network pi-zambon-network \
              -e ENV=PROD \
              -e DATABASE_URL=mysql+pymysql://app_user:app_password123@mysql-pi-zambon:3306/pf_zambon_db \
              -p 8080:8080 \
              gustavovvbs/pi-zambon:${{ github.sha }}